version: 2

sources:
  - name: airbyte
    # En MotherDuck, el catálogo es la base de datos (intdt) y el esquema es 'main'.
    database: intdt
    schema: main
    tables:
      - name: proyectos_bid
        columns:
          - name: oper_num
            tests:
              - unique
              - not_null
          - name: cntry_cd
            tests:
              - not_null
          - name: totl_cost_orig

      - name: desempleo
        columns:
          - name: country
            tests:
              - not_null
          - name: value

      - name: cpi_indice
        columns:
          - name: country_name
            tests:
              - not_null
          - name: value



